version: "3.7"
services:
  database:
    image: postgres:9.6.17
    restart: always
    env_file:
      - database/database.env # configure postgres

  datagathering:
    build: datagathering/
    restart: always
    depends_on:
      - database

  grafana:
    image: grafana/grafana:master
    restart: always
    depends_on:
      - database
    ports:
    - 3000:3000